# by john  2018-09-15
#自定义全局参数放在anytrek中!!
anytrek:
   #com.anytrek.ts3.conf.GlobalConfig
   global:
       deviceUpdateFilePath: /data/deviceUpdateFile
       imageUpfilePath: /anytrek/Platform/Software/TrackerServer3/www/upload/images
       upfileImageURL: https://ts2.anytrek.com/upload/images/
   #com.anytrek.ts3.mail.EmailConfig
   email:
      #设置有效期，  单位天
      exdate: 3
      from: no_reply@anytrek.com
      activationTitle: Anytrek Register Email
      activationUrl: https://ts2.anytrek.com/register.html
      resetPwdTitle: Anytrek Reset Email
      resetPwdUrl : https://ts2.anytrek.com/resetpwd.html


server:
   port: 82
   sessionTimeout: 7200 #单位 秒
   tomcat:
      max-threads: 0
      uri-encoding: UTF-8


spring:
   #弃用此方式区分环境的配置文件， 直接把配置放到外部简单粗暴 :)
   #profiles:
      #active: test
   servlet:
      multipart:
         # 上传一个文件最大值,默认1Mb
         max-file-size: 100MB
         # 上传多个文件最大值,50Mb,默认10Mb
         max-request-size: 100MB
   http:
      encoding:
         force: true
         charset: UTF-8
         enabled: true
   redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      timeout: 2000 #单位 毫秒
      expire: 7200 #单位 秒
   datasource:
      driverClassName:  com.mysql.jdbc.Driver
      url : jdbc:mysql://localhost:3306/location_v3_demo_db?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf-8
      username : sean
      password : 12345
      initialSize: 5
      minIdle: 1
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
   banner:
      location: classpath:public/anytrek.txt

#自定义sql的时候需要这些配置
mybatis:
   type-aliases-package: com.anytrek.ts3.model
   mapper-locations: classpath:mapper/*.xml
   configuration:
      map-underscore-to-camel-case: true

mapper:
   mappers: com.anytrek.ts3.util.MyMapper
   notEmpty: true
   identity: MYSQL

#日志配置路径
logging:
   config: config/log4j2.yml
