# by john  2018-09-20
# 共有8个级别，按照从低到高为：ALL < TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF。
#日志只存储在两个日志文件中： log.log（按天归档）   error.log（按大小归档）
Configuration:
  status: warn
  monitorInterval: 30
  Properties: # 定义全局变量
    Property: 
      - name: log.path
        value: /anytrekdata/logs/TrackerServer3/AdminServer/
  Appenders:
    #输出到控制台
    Console:  
      name: CONSOLE
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%d{YYYY-MM-dd HH:mm:ss}:%4p (%F:%L) - %m%n" 
    RollingFile:
        # 总输出文件，按天归档
      - name: ROLLING_FILE
        fileName: ${log.path}/log.log
        filePattern: "${log.path}/log.log.%d{YYYY-MM-dd}"
        PatternLayout:
          pattern: "%d{YYYY-MM-dd HH:mm:ss}:%4p - %m%n"
        Filters:
          # 一定要先去除不接受的日志级别，然后获取需要接受的日志级别
          ThresholdFilter:
            - level: error
              onMatch: DENY
              onMismatch: NEUTRAL
            - level: info
              onMatch: ACCEPT
              onMismatch: DENY
        Policies:
          TimeBasedTriggeringPolicy:  # 按天分类
            modulate: true
            interval: 1
        DefaultRolloverStrategy:     # 文件最多100个
          max: 100
        # 错误输出文件，超过64M归档 
      - name: ROLLING_ERROR_FILE
        ignoreExceptions: false
        fileName: ${log.path}/error.log
        filePattern: "${log.path}/error.log.%d{YYYY-MM-dd}"
        ThresholdFilter:
          level: error
          onMatch: ACCEPT
          onMismatch: DENY
        PatternLayout:
          pattern: "%d{YYYY-MM-dd HH:mm:ss}:%4p (%F:%L) - %m%n"
        Policies:
          SizeBasedTriggeringPolicy:
             size: "8 MB"
        DefaultRolloverStrategy:     # 文件最多100个
          max: 300
  Loggers:
    #只吐出error以上的日志
    Root:
      level: ERROR
      AppenderRef:
        - ref: CONSOLE
        - ref: ROLLING_FILE
        - ref: ROLLING_ERROR_FILE
    Logger: #单独设置某些包的输出级别
      #项目代码吐出info以上的日志，   必要时可改为trace
    - name: com.anytrek.ts3 #复数加上-
      level: info  #显示sql日志：trace
      additivity: false #去除重复的log
      AppenderRef:
        - ref: CONSOLE 
        - ref: ROLLING_FILE 
        - ref: ROLLING_ERROR_FILE
