
/* 2019-08-6 Aleen t_order,t_order_items, t_payment, t_payment_items */
CREATE TABLE `t_order` (
  `order_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '订单id',
  `type` tinyint(4) DEFAULT NULL COMMENT '订单类型',
  `customer` varchar(36) DEFAULT NULL COMMENT '顾客',
  `status` tinyint(4) DEFAULT NULL COMMENT '订单状态',
  `description` varchar(255) DEFAULT NULL COMMENT '描述',
  `invoice_no` varchar(20) DEFAULT NULL COMMENT '订单号',
  `invoice_date` timestamp NULL DEFAULT NULL COMMENT '发票日期',
  `due_date` timestamp NULL DEFAULT NULL COMMENT '到期时间',
  `device_id` bigint(20) DEFAULT NULL COMMENT '设备号',
  `sales` varchar(36) DEFAULT NULL COMMENT '创建订单的销售',
  `billing_company` varchar(64) DEFAULT NULL COMMENT '账单公司',
  `billing_contact` varchar(36) DEFAULT NULL COMMENT '账单联系人',
  `billing_number` varchar(36) DEFAULT NULL COMMENT '账单号',
  `billing_email` varchar(36) DEFAULT NULL COMMENT '账单邮箱',
  `billing_address` varchar(128) DEFAULT NULL COMMENT '账单地址',
  `billing_city` varchar(18) DEFAULT NULL COMMENT '账单城市',
  `billing_state` varchar(18) DEFAULT NULL COMMENT '账单州',
  `billing_country` varchar(18) DEFAULT NULL COMMENT '账单所在国家',
  `billing_zip` varchar(8) DEFAULT NULL COMMENT '账单邮编',
  `shipping_company` varchar(64) DEFAULT NULL COMMENT '航运公司',
  `shipping_contact` varchar(36) DEFAULT NULL COMMENT '航运公司联系人',
  `shipping_number` varchar(36) DEFAULT NULL COMMENT '航运公司号',
  `shipping_email` varchar(36) DEFAULT NULL COMMENT '航运公司邮箱',
  `shipping_address` varchar(128) DEFAULT NULL COMMENT '航运公司地址',
  `shipping_city` varchar(18) DEFAULT NULL COMMENT '航运公司所在城市',
  `shipping_state` varchar(18) DEFAULT NULL COMMENT '航运公司联系人所在州',
  `shipping_country` varchar(18) DEFAULT NULL COMMENT '航运公司所在国家',
  `shipping_zip` varchar(8) DEFAULT NULL COMMENT '航运公司邮编',
  `shipping_via` varchar(64) DEFAULT NULL COMMENT '航运公司经由',
  `shipping_fee` float DEFAULT NULL COMMENT '航运公司费用',
  `payment_term` varchar(255) DEFAULT NULL COMMENT '付款方式',
  `note` varchar(255) DEFAULT NULL COMMENT '说明备注',
  `modify_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `t_order_items` (
  `item_id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) DEFAULT NULL COMMENT '设备号',
  `model_id` int(11) DEFAULT NULL COMMENT '型号id',
  `quantity` int(11) DEFAULT NULL COMMENT '订单号',
  `rate` float DEFAULT NULL COMMENT '税率',
  `amount` float DEFAULT NULL COMMENT '合计',
  `tax` float DEFAULT NULL COMMENT '税款',
  `description` varchar(255) DEFAULT NULL COMMENT '描述说明',
  PRIMARY KEY (`item_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `t_payment` (
  `payment_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '付账单id',
  `customer` varchar(36) DEFAULT NULL COMMENT '顾客',
  `status` tinyint(4) DEFAULT NULL COMMENT '状态',
  `invoice_no` varchar(20) DEFAULT NULL COMMENT '发票号',
  `invoice_date` timestamp NULL DEFAULT NULL COMMENT '发票日期',
  `due_date` timestamp NULL DEFAULT NULL COMMENT '到期日期',
  `sales` varchar(36) DEFAULT NULL COMMENT '销售名字id',
  `device_id` bigint(20) DEFAULT NULL COMMENT '设备号',
  `billing_company` varchar(64) DEFAULT NULL COMMENT '账单公司',
  `billing_contact` varchar(36) DEFAULT NULL COMMENT '账单联系人',
  `billing_number` varchar(36) DEFAULT NULL COMMENT '账单号',
  `billing_email` varchar(36) DEFAULT NULL COMMENT '账单邮箱',
  `billing_address` varchar(128) DEFAULT NULL COMMENT '账单地址',
  `billing_city` varchar(18) DEFAULT NULL COMMENT '账单城市',
  `billing_state` varchar(18) DEFAULT NULL COMMENT '账单州',
  `billing_country` varchar(18) DEFAULT NULL COMMENT '账单所在国家',
  `billing_zip` varchar(8) DEFAULT NULL COMMENT '账单邮编',
  `shipping_company` varchar(64) DEFAULT NULL COMMENT '航运公司',
  `shipping_contact` varchar(19) DEFAULT NULL COMMENT '航运公司联系人',
  `shipping_number` varchar(19) DEFAULT NULL COMMENT '航运公司号',
  `shipping_email` varchar(36) DEFAULT NULL COMMENT '航运公司邮箱',
  `shipping_address` varchar(128) DEFAULT NULL COMMENT '航运公司地址',
  `shipping_city` varchar(18) DEFAULT NULL,
  `shipping_state` varchar(18) DEFAULT NULL COMMENT '航运公司联系人所在州',
  `shipping_country` varchar(18) DEFAULT NULL COMMENT '航运公司所在国家',
  `shipping_zip` varchar(8) DEFAULT NULL COMMENT '航运公司邮编',
  `shipping_via` varchar(64) DEFAULT NULL COMMENT '航运公司经由',
  `shipping_fee` float DEFAULT NULL COMMENT '航运公司费用',
  `payment_term` varchar(255) DEFAULT NULL COMMENT '付款方式',
  `note` varchar(255) DEFAULT NULL COMMENT '说明备注',
  `amount` float DEFAULT NULL COMMENT '合计',
  PRIMARY KEY (`payment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_payment_items` (
  `item_id` int(11) NOT NULL AUTO_INCREMENT,
  `payment_id` int(11) DEFAULT NULL,
  `model_id` int(11) DEFAULT NULL COMMENT '产品',
  `quantity` int(11) DEFAULT NULL COMMENT '数量',
  `rate` float DEFAULT NULL COMMENT '税率',
  `amount` float DEFAULT NULL COMMENT '金额',
  `tax` float DEFAULT NULL COMMENT '税',
  `description` text COMMENT '备注',
  PRIMARY KEY (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
